### ISSUE TITLE
Build Error on Centos 6.8

### ISSUE THREAD

**Issue by mawhite** [cryoem-uoft/cryosparc-issues#135] opened 2017-02-10 18:16 UTC
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.6.2 (node-v46 ABI) (falling back to source compile with node-gyp)

**Comment by alipunjani** [comment] 2017-02-10 19:30
Thanks for reporting - this is likely a problem with your gcc version. Can you try the instructions here:
https://discuss.cryosparc.com/t/errors-during-npm-install-with-gcc-version/74

Please let us know what happens.

**Comment by alipunjani** [comment] 2017-02-14 20:41
@mawhite was this issue resolved?

**Comment by UNCuser** [comment] 2017-02-20 17:06
Similar (identical) error here using CentOS7.  
gcc --version = 4.8.5

**Comment by truatpasteurdotfr** [comment] 2017-02-20 17:12
https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz is 404, not related to any gcc versions, just my 2 cents

**Comment by UNCuser** [comment] 2017-02-20 21:58
So just...
1) yum -y install nodejs
2) npm install bcrypt
?

**Comment by alipunjani** [comment] 2017-04-03 15:14
Closing for now, is anyone still having installation issues?

**Closed by alipunjani** 2017-04-03 15:14 UTC

**Comment by drpaquet** [comment] 2017-10-09 19:26
I am still having issues with installation on CentOS 6.7.  I have gotten cryoSPARC to install but the webapp does not work.  I have this error in the meteor.stdout: 

Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/grosslab/cryosparc/cryosparc-webapp/bundle/programs/server/npm/node_modules/grpc/src/node/extension_binary/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/grosslab/cryosparc/cryosparc-webapp/bundle/programs/server/npm/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

Is there a work around for this yet that does not require me to pull the GLIBCXX_3.4.15 from Chrome (detailed here: [Link](https://github.com/cryoem-uoft/cryosparc-issues/issues/62) which is no longer supported on CentOS 6.7?

**Comment by jhm13c** [comment] 2017-10-09 19:52
I ran to the same problem and this is how a fixed it (someone else found the solution, I will link it at the bottom):
1. Install Chrome
2. run this command `ln -s /opt/google/chrome/lib/libstdc++.so.6 /usr/lib64/`
The issue is that CentOS6 doesn't have the up to date libstdc++ but Chrome does

For further reading and original solution, [https://github.com/cryoem-uoft/cryosparc-issues/issues/62](url) go all the way to the bottom until you see the reply titled:

>  tanyongzi commented on Nov 11, 2016
